# 08 NLP Evaluation Metrics: BLEU, ROUGE & Perplexity

**Scenario**: Automated Generation Metric Benchmarking & Manual Calculation Verification.

This notebook demonstrates manual step-by-step BLEU-2, ROUGE-1/L, and Perplexity calculations, verifying results against NLTK and `rouge-score` libraries.

## Step 1: Step-by-Step Manual BLEU-2, ROUGE-1/L & Perplexity Calculation

In [1]:
import numpy as np

candidate = "the cat sat on mat"
reference = "the cat sat on the mat"

cand_words = candidate.split()
ref_words = reference.split()

c_len = len(cand_words)  # 5
r_len = len(ref_words)   # 6

# 1. Unigram Precision p1
p1 = 5 / 5  # 1.0

# 2. Bigram Precision p2
p2 = 3 / 4  # 0.75

# 3. Brevity Penalty BP
bp = np.exp(1 - (r_len / c_len))  # exp(-0.2) = 0.8187

# 4. BLEU-2 Score
bleu_2 = bp * np.exp(0.5 * np.log(p1) + 0.5 * np.log(p2))

# 5. ROUGE-1 & ROUGE-L Recall
rouge_1_recall = 5 / 6  # 0.8333
rouge_l_recall = 5 / 6  # 0.8333

# 6. Perplexity from CE Loss
ce_loss = 2.3026
ppl = np.exp(ce_loss)  # 10.0

print("=== Manual Metric Computation Verification ===")
print(f"Candidate Length: {c_len} | Reference Length: {r_len}")
print(f"Modified Unigram Precision p1: {p1:.4f}")
print(f"Modified Bigram Precision p2 : {p2:.4f}")
print(f"Brevity Penalty BP           : {bp:.4f}")
print(f"Manual BLEU-2 Score          : {bleu_2:.4f}")
print(f"Manual ROUGE-1 Recall        : {rouge_1_recall:.4f}")
print(f"Manual ROUGE-L Recall        : {rouge_l_recall:.4f}")
print(f"Perplexity (Loss=2.3026)     : {ppl:.2f}")

=== Manual Metric Computation Verification ===
Candidate Length: 5 | Reference Length: 6
Modified Unigram Precision p1: 1.0000
Modified Bigram Precision p2 : 0.7500
Brevity Penalty BP           : 0.8187
Manual BLEU-2 Score          : 0.7090
Manual ROUGE-1 Recall        : 0.8333
Manual ROUGE-L Recall        : 0.8333
Perplexity (Loss=2.3026)     : 10.00


## Step 2: NLTK & Rouge-Score Python Verification

In [2]:
from nltk.translate.bleu_score import sentence_bleu
from rouge_score import rouge_scorer

# NLTK BLEU-2
nltk_bleu_2 = sentence_bleu([ref_words], cand_words, weights=(0.5, 0.5))

# Rouge Scorer
scorer = rouge_scorer.RougeScorer(['rouge1', 'rougeL'], use_stemmer=False)
scores = scorer.score(reference, candidate)

print("=== Library Pipeline Verification ===")
print(f"NLTK BLEU-2 Score    : {nltk_bleu_2:.4f}")
print(f"ROUGE-1 Recall Score : {scores['rouge1'].recall:.4f}")
print(f"ROUGE-L Recall Score : {scores['rougeL'].recall:.4f}")

=== Library Pipeline Verification ===
NLTK BLEU-2 Score    : 0.7090
ROUGE-1 Recall Score : 0.8333
ROUGE-L Recall Score : 0.8333


## Output Explanation & Complexity Analysis

- **Brevity Penalty**: Short candidate length $c=5 < r=6$ penalizes BLEU-2 by factor $0.8187$.
- **Perplexity Interpretation**: Loss $2.3026$ yields $\text{PPL} = 10.0$, indicating a branching uncertainty factor of 10.
- **Time Complexity**: $O(|c| \cdot |r|)$ sequence token matching.
- **Space Complexity**: $O(|c| + |r|)$ token list storage.